sudo: required
language: android
dist: trusty

android:
        components:
                - build-tools-26.1.2
os:
        - linux
env:
        - SYS=25 ABI="google_apis;arm64-v8a"

before_install:
        - echo y | sdkmanager "emulator" "tools" "platform-tools"
        - sdkmanager --list
          #older packages( for emulator) TODO change build tools to 29.0.3
        - echo y | sdkmanager "platforms;android-25" #"build-tools;25.0.2" 
        
          #creating and starting emulator
        - sdkmanager "system-images;android-$SYS;$ABI"
        - sdkmanager --list
        - echo no | avdmanager create avd --force -n myAndroidAVD -k "system-images;android-$SYS;$ABI"

        - emulator @myAndroidAVD -no-audio -no-window -gpu swiftshader &
before_script:
        - android-wait-for-emulator
        - adb shell input keyevent 82
script:

notifications:
        email: false
        #before_script:
        #- echo "y" | android update sdk -a --no-ui --filter sys-img-x86-android-28
          #- android list targets
          #- echo "n" | android create avd --name myAndroid28 -t android-28
          #- emulator @myAndroid28 -no-window -no-audio -kernel /usr/local/android-sdk-25.2.3/system-images/android-28/default/x86/kernel-ranchu-64
          #- android-wait-for-emulator
          #- export ANDROID_SDK_ROOT="/usr/local/android-sdk/system-images"
           #- echo $ANDROID_SDK_ROOT
 
        #- echo no | android create avd --name myAndroid28 -t android-28 --abi arm64-v8a
        #- emulator @myAndroid28 -no-window -no-audio -kernel /usr/local/android-sdk-25.2.3/system-images/android-28/default/x86/kernel-ranchu-64
        #- android-wait-for-emulator
           #- adb shell input keyevent 82 &
