language: android
dist: trusty
android:
        components:
                - build-tools-29.0.3
before_install:
                - yes | sdkmanager "platforms;android-28"
script:
        - cd /usr/local/android-sdk
        - ls build-tools
        - ls platform-tools
        - ls system-images
        - ls tools
        - ls extras
notifications:
        email: false
before_script:
         - echo yes | android update sdk -a --no-ui --filter sys-img-x86-android-28
         - export ANDROID_SDK_ROOT=$ANDROID_HOME
         - echo $ANDROID_SDK_ROOT 
 
         - echo no | android create avd --name myAndroid28 -t android-28 --abi default/x86 
         - emulator -avd myAndroid28 -no-audio -no-window &
           #- android-wait-for-emulator
           #- adb shell input keyevent 82 &
