language: android
dist: trusty
android:
        components:
                - build-tools-29.0.3
before_install:
                - yes | sdkmanager "platforms;android-28"
                - echo yes | android update sdk -a --no-ui --filter sys-img-x86-android-28
                - sudo apt-get install tree

script:
        - cd /usr/local
        - tree -L 3
       
         #wait for avd
         #- android-wait-for-emulator
         #- adb shell input keyevent 82 &
notifications:
        email: false
before_script:
                    #- export ANDROID_SDK_ROOT="/usr/local/android-sdk/system-images"
           #- echo $ANDROID_SDK_ROOT
 
         - echo no | android create avd --name myAndroid28 -t android-28 --abi default/x86 
           #- emulator -avd myAndroid28 -no-audio -no-window &
           #- android-wait-for-emulator
           #- adb shell input keyevent 82 &
