language: android
dist: trusty
android:
        components:
                - build-tools-29.0.3
before_install:
                - yes | sdkmanager "platforms;android-28"
script:
        - cd /usr/local/android-sdk
        - ls system-images/android-28/default/x86/kernel-ranchu-64
        - ls tools/
        - mv tools/qemu tools/kernel-qemu
        - export $ANDROID_SDK_ROOT=/usr/local/android-sdk/tools

         #wait for avd
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
notifications:
        email: false
before_script:
         - echo yes | android update sdk -a --no-ui --filter sys-img-x86-android-28
 
         - echo no | android create avd --name myAndroid28 -t android-28 --abi default/x86 
         - emulator -avd myAndroid28 -no-audio -no-window &
           #- android-wait-for-emulator
           #- adb shell input keyevent 82 &
