language: android
dist: trusty
android:
        components:
                - build-tools-29.0.3
                - android-28

before_install:
        - yes | sdkmanager "platforms;android-28"

notifications:
        slack:
                on_failure: never
                on_succes: never
before_script:
          - echo yes | android update sdk -a --no-ui --filter sys-img-x86_64-android-28
          - android list targets
            #- echo yes | android create avd --force -n test -t android-28 --abi x86_64 
            #- emulator -avd test -no-skin -no-audio -no-window &
            #- android-wait-for-emulator
            #- adb shell input keyevent 82 &
