language: android
dist: trusty
android:
        components:
                - build-tools-29.0.3
                - android-29
                  #- sys-img-armeabi-v7a-addon-google_apis-google-28

before_install:
        - yes | sdkmanager "platforms;android-28"
scipt:
        - android list sdk --extended --no-ui --all
          #before_script:
          #- echo yes | android create avd --force -n test -t android-25 --abi arm64-v8a
          #- emulator -avd test -no-skin -no-audio -no-window &
          #- android-wait-for-emulator
          #- adb shell input keyevent 82 &
