language: android
dist: trusty
android:
        components:
                - build-tools-29.0.3
                - android-28
                - sys-img-x86_64-google_apis-28

before_install:
        - yes | sdkmanager "platforms;android-28"
script:
        - 
notifications:
        slack:
                on_failure: never
                on_succes: never
before_script:
          - echo yes | android create avd --force -n test -t android-25 --abi x86_64 
          - emulator -avd test -no-skin -no-audio -no-window &
          - android-wait-for-emulator
          - adb shell input keyevent 82 &
